#!/bin/sh
set -e

ROLE="${HONCHO_ROLE:-api}"
CONFIG_DIR="${HONCHO_CONFIG_DIR:-/config}"
ENV_FILE="${CONFIG_DIR}/.env"

echo "=== Honcho Dappnode — ${ROLE} ==="

# ── 1. Load env vars from shared .env (written by setup wizard) ───
if [ -f "${ENV_FILE}" ]; then
  echo "[Config] Loading ${ENV_FILE}"
  while IFS= read -r line; do
    case "$line" in \#*|"") continue ;; esac
    key=$(echo "$line" | cut -d= -f1)
    val=$(echo "$line" | cut -d= -f2-)
    export "$key"="$val"
  done < "${ENV_FILE}"
fi

# ── 2. Resolve provider settings ─────────────────────────────────
# The setup wizard writes:
#   LLM_VLLM_API_KEY, LLM_VLLM_BASE_URL, LLM_MODEL,
#   LLM_OPENAI_API_KEY, LLM_EMBEDDING_API_KEY
#
# Upstream Honcho uses config.toml model_config sections with:
#   transport = "openai" | "anthropic" | "gemini"
#   model = "model-name"
#   [overrides] base_url = "..."
#
# Strategy: route ALL workers through "openai" transport (the OpenAI
# SDK client, which works with any OpenAI-compatible endpoint) and
# set base_url override for non-OpenAI providers.

API_KEY="${LLM_VLLM_API_KEY:-${LLM_OPENAI_API_KEY:-}}"
BASE_URL="${LLM_VLLM_BASE_URL:-}"
MODEL="${LLM_MODEL:-gpt-5.4-mini}"
EMBED_KEY="${LLM_EMBEDDING_API_KEY:-${API_KEY}}"
EMBED_BASE_URL="${LLM_EMBEDDING_BASE_URL:-${BASE_URL}}"

# Export the key upstream Honcho reads for the OpenAI client
export LLM_OPENAI_API_KEY="${API_KEY}"

echo "[LLM] Model: ${MODEL}"
echo "[LLM] Base URL: ${BASE_URL:-OpenAI default}"
echo "[LLM] Embeddings: ${EMBED_BASE_URL:-OpenAI default}"

# ── 3. Placeholder for first boot (no wizard config yet) ─────────
if [ -z "${API_KEY}" ]; then
  echo "[Config] WARNING: No LLM provider configured."
  echo "[Config] Open http://setup-wizard.honcho.dappnode:8080 to configure."
  export LLM_OPENAI_API_KEY="not-configured"
  API_KEY="not-configured"
  BASE_URL="https://localhost:9999"
  EMBED_KEY="not-configured"
  EMBED_BASE_URL="https://localhost:9999"
fi

# ── 4. Generate config.toml ──────────────────────────────────────
# Build the overrides block only if a custom base_url is set
if [ -n "${BASE_URL}" ]; then
  OVERRIDE_BLOCK="
[deriver.model_config.overrides]
base_url = \"${BASE_URL}\"

[dialectic.levels.minimal.model_config.overrides]
base_url = \"${BASE_URL}\"

[dialectic.levels.low.model_config.overrides]
base_url = \"${BASE_URL}\"

[dialectic.levels.medium.model_config.overrides]
base_url = \"${BASE_URL}\"

[dialectic.levels.high.model_config.overrides]
base_url = \"${BASE_URL}\"

[dialectic.levels.max.model_config.overrides]
base_url = \"${BASE_URL}\"

[summary.model_config.overrides]
base_url = \"${BASE_URL}\"

[dream.deduction_model_config.overrides]
base_url = \"${BASE_URL}\"

[dream.induction_model_config.overrides]
base_url = \"${BASE_URL}\""
else
  OVERRIDE_BLOCK=""
fi

if [ -n "${EMBED_BASE_URL}" ]; then
  EMBED_OVERRIDE="
[embedding.model_config.overrides]
base_url = \"${EMBED_BASE_URL}\""
else
  EMBED_OVERRIDE=""
fi

cat > /app/config.toml << TOMLEOF
# Auto-generated by Dappnode entrypoint — $(date -u '+%Y-%m-%d %H:%M:%S UTC')
# Single-provider mode: all workers use the same LLM endpoint.

[app]
LOG_LEVEL = "INFO"
SESSION_OBSERVERS_LIMIT = 10
GET_CONTEXT_MAX_TOKENS = 100000
MAX_FILE_SIZE = 5242880
MAX_MESSAGE_SIZE = 25000
EMBED_MESSAGES = true
NAMESPACE = "honcho"

[db]
CONNECTION_URI = "${DB_CONNECTION_URI}"
SCHEMA = "public"
POOL_SIZE = 10
MAX_OVERFLOW = 20
POOL_TIMEOUT = 30
POOL_RECYCLE = 300

[auth]
USE_AUTH = false

[sentry]
ENABLED = false

[llm]
DEFAULT_MAX_TOKENS = 2500
OPENAI_API_KEY = "${API_KEY}"

[embedding]
VECTOR_DIMENSIONS = 1536
MAX_INPUT_TOKENS = 8192

[embedding.model_config]
transport = "openai"
model = "text-embedding-3-small"
${EMBED_OVERRIDE}

[deriver]
ENABLED = true
WORKERS = 1
POLLING_SLEEP_INTERVAL_SECONDS = 1.0
STALE_SESSION_TIMEOUT_MINUTES = 5
DEDUPLICATE = true
MAX_INPUT_TOKENS = 25000
WORKING_REPRESENTATION_MAX_OBSERVATIONS = 100
REPRESENTATION_BATCH_MAX_TOKENS = 1024
FLUSH_ENABLED = false

[deriver.model_config]
transport = "openai"
model = "${MODEL}"

[peer_card]
ENABLED = true

[dialectic]
MAX_OUTPUT_TOKENS = 8192
MAX_INPUT_TOKENS = 100000
HISTORY_TOKEN_LIMIT = 8192
SESSION_HISTORY_MAX_TOKENS = 4096

[dialectic.levels.minimal]
MAX_TOOL_ITERATIONS = 1
MAX_OUTPUT_TOKENS = 250

[dialectic.levels.minimal.model_config]
transport = "openai"
model = "${MODEL}"

[dialectic.levels.low]
MAX_TOOL_ITERATIONS = 5

[dialectic.levels.low.model_config]
transport = "openai"
model = "${MODEL}"

[dialectic.levels.medium]
MAX_TOOL_ITERATIONS = 2

[dialectic.levels.medium.model_config]
transport = "openai"
model = "${MODEL}"

[dialectic.levels.high]
MAX_TOOL_ITERATIONS = 4

[dialectic.levels.high.model_config]
transport = "openai"
model = "${MODEL}"

[dialectic.levels.max]
MAX_TOOL_ITERATIONS = 10

[dialectic.levels.max.model_config]
transport = "openai"
model = "${MODEL}"

[summary]
ENABLED = true
MESSAGES_PER_SHORT_SUMMARY = 20
MESSAGES_PER_LONG_SUMMARY = 60
MAX_TOKENS_SHORT = 1000
MAX_TOKENS_LONG = 4000

[summary.model_config]
transport = "openai"
model = "${MODEL}"

[dream]
ENABLED = true
DOCUMENT_THRESHOLD = 50
IDLE_TIMEOUT_MINUTES = 60
MIN_HOURS_BETWEEN_DREAMS = 8
ENABLED_TYPES = ["omni"]
MAX_TOOL_ITERATIONS = 20
HISTORY_TOKEN_LIMIT = 16384

[dream.deduction_model_config]
transport = "openai"
model = "${MODEL}"

[dream.induction_model_config]
transport = "openai"
model = "${MODEL}"

[cache]
ENABLED = true
URL = "${CACHE_URL}"
DEFAULT_TTL_SECONDS = 300

[vector_store]
TYPE = "pgvector"
NAMESPACE = "honcho"

[metrics]
ENABLED = false

[telemetry]
ENABLED = false

[webhook]
SECRET = ""
${OVERRIDE_BLOCK}
TOMLEOF

echo "[Config] Generated /app/config.toml"

# ── 5. Role-based startup ────────────────────────────────────────
if [ "${ROLE}" = "api" ]; then

  echo "[DB] Waiting for PostgreSQL ..."
  until pg_isready -h database -U honcho -q 2>/dev/null; do
    sleep 2
  done
  echo "[DB] PostgreSQL is ready."

  pg_dump -h database -U honcho -d honcho --clean --if-exists \
    -f /backup/honcho.sql 2>/dev/null || \
    echo "[Backup] No existing data to dump (first boot)."

  echo "[Migrations] Running ..."
  cd /app
  python -m alembic upgrade head 2>&1 || \
    echo "[Migrations] Alembic failed — may already be up to date."
  echo "[Migrations] Done."

  echo "[Server] Starting Honcho API on :8000 ..."
  exec uvicorn src.main:app \
    --host 0.0.0.0 \
    --port 8000 \
    --workers 1

elif [ "${ROLE}" = "deriver" ]; then

  sleep 5
  echo "[Deriver] Starting background worker ..."
  exec python -m src.deriver

else
  echo "[ERROR] Unknown HONCHO_ROLE: ${ROLE}"
  exit 1
fi
